var N_BEATS_PER_MEASURE = 16
var N_MEASURES = 3
var N_OCTAVES = 3

var H_SCALE = 2
var V_SCALE = 2.65

var W_L_BAR = H_SCALE * 1
var W_R_BAR_1 = H_SCALE * 3
var W_R_BAR_2 = H_SCALE * 1
var W_WHITE = H_SCALE * 191
var W_BLACK = H_SCALE * 109
var W_BEAT = H_SCALE * 10
var W_BEAT_DIV = H_SCALE * 1
var W_MEASURE = ((N_BEATS_PER_MEASURE * (W_BEAT + W_BEAT_DIV)) - W_BEAT_DIV)
var W_MEASURE_DIV = H_SCALE * 1

var H_WHITE = V_SCALE * 25
var H_WHITE_DIV = V_SCALE * 1
var H_BLACK = V_SCALE * 15
var H_OCTAVE_DIV = V_SCALE * 1
var H_OCTAVE = ((7 * (H_WHITE + H_WHITE_DIV)) - H_WHITE_DIV)

var YO_BLACK = [70, 50, 30, null, 60, 40, null]

var C_BG = '000000'
var C_WHITE = 'ffffff'
var C_BLACK = '000000'
var C_L_BAR = 'abb1b1'
var C_R_BAR_1 = 'abb1b1'
var C_R_BAR_2_WHITE = '5c5c5c'
var C_R_BAR_2_BLACK = '555555'
var C_WHITE_DIV = '5d5d5d'
var C_ROW_WHITE = '464646'
var C_ROW_BLACK = '3e3e3e'
var C_ROW_WHITE_DIV = '3e3e3e'
var C_ROW_OCTAVE_DIV = '383838'
var C_OCTAVE_DIV = '111111'
var C_WHITE_DIV_BEAT_DIV = '363636'
var C_BEAT_DIV_BLACK = '363636'
var C_BEAT_DIV_WHITE = '3d3d3d'
var C_MEASURE_DIV_WHITE = '383838'
var C_MEASURE_DIV_BLACK = '313131'

var W = (W_L_BAR + W_WHITE + W_R_BAR_1 + W_R_BAR_2 + ((N_MEASURES * (W_MEASURE + W_MEASURE_DIV)) - W_MEASURE_DIV))
var H = (N_OCTAVES * (H_OCTAVE + H_OCTAVE_DIV)) - H_OCTAVE_DIV
